### PR TITLE
Add a reversed byte order representation to the contract panel

### LINKED ISSUE #162: Add a button to copy Big-endian and Little-endian versions of script hash
As a user, I would like to have a way to copy the big-endian and little-endian versions of the script hash.

In our ecosystem, tools use different ways of inputting script hashes -- sometimes big-endian, sometimes little-endian.

Therefore, based on the suggestion of [this comment](https://github.com/neo-project/neo-express/issues/276#issuecomment-1563265844), I propose a super small addition to the smart contract view of the Visual Tracker:

Kapture 2023-05-30 at 10 07 54

☝️ in this view, add a "copy big-endian" and "copy little-endian", or something like this.

I'm not aware if there are other views within the visual code extension where script hashes are displayed. If there are, I would suggest adding the same button ("copy big-endian", "copy little-endian") in these other views.

### PR DESCRIPTION
**Pull request by gsmachado**
Fixes #162

### CODE REVIEW

**Comment by gsmachado** [comment]
I'm proud to say that this PR does not import any external libraries, and everything was done with CSS.

Here's the GIF:

Kapture_2023-06-07_at_01 01 51

**Comment by gsmachado** [comment]
@rick9 can you please provide feedback on whether this VSIX version works and makes your "life" easier? Thanks.

**Comment by lock9** [comment]
It does solve a problem. The user won't need to use an external tool to convert the hashes. However, other UI elements still use the old format, which can be misleading. 
This will be enough for now (for us), but we need to make some other changes if we want to make the onboarding easier.

**Review by JohndeVadoss — APPROVED** [review]

**Comment by gsmachado** [comment]
> However, other UI elements still use the old format, which can be misleading.

@lock9 it would be great if you could create an issue telling us (maybe with screenshots to make it easier) about these other UI elements which use the "old" (non-reversed) format.

Once we get this, we can plan accordingly.

Thanks! 🙏

**Pull request merged**
