### PR TITLE
update NEO and GAS script hashes

### PR DESCRIPTION
**Pull request by djnicholson**

### CODE REVIEW

**Comment by djnicholson** [comment]
In the current RC1 build, the NEO and GAS balance always shows as zero in the address view.  This fixes that.  The current RC1 build is not totally unusable though - the GAS and NEO balance are still shown in the list of all NEP-17 balances.

**Comment by devhawk** [comment]
> the GAS and NEO balance are still shown in the list of all NEP-17 balances.

What do we need to do to fix this?

**Comment by djnicholson** [comment]
> What do we need to do to fix this?

Because this is confusing (the zeroes are wrong):

image

**Comment by djnicholson** [comment]
> > the GAS and NEO balance are still shown in the list of all NEP-17 balances.
> 
> What do we need to do to fix this?

That was by design, but I can omit them if preferred.

**Pull request merged**
